default['cog_ips']['suricata_version'] = '3.1.1'
default['cog_ips']['rules_deploy_vault'] = 'cog_ips'
default['cog_ips']['rules_deploy_bucket'] = 'deploykeys'
default['cog_ips']['rules_deploy_key']    = 'NAME_OF_KEY'
default['cog_ips']['rules_repo']          = 'NAME_OF_RULES_REPO'
